---
- name: configure webserver with nginx and tls
  hosts: webservers
  become: True
  vars:
    key_file: /etc/nginx/ssl/nginx.key
    cert_file: /etc/nginx/ssl/nginx.crt
    conf_file: /etc/nginx/sites-available/default
    server_name: localhost
  tasks:
    - name: Install nginx
      yum: name=nginx state=present
 
    - name: create directory for ssl certificates
      file: path=/etc/nginx/ssl state=directory
 
    - name: copy tls key
      copy: src=files/nginx/ngix.key dest={{ nginx.key }} mode=0600
      notify: restart nginx

    - name: copy tls certificate
      copy: src=files/nginx/nginx.crt dest={{ nginx.crt }} 
      notify: restart nginx

    - name: copy nginx config file
      copy: src=files/template/nginx.conf.j2 dest={{ conf_file }}
      notify: restart nginx

    - name: enable configutation
      file: dest=/etc/nginx/sistes-enable/default src={{ conf_file }} state=link
      notify: restart nginx

    - name: copy index.html
      template: src=template/index.html.j2 dest=/usr/local/share/nginx/html/index.html mode=0644
    
  headlers:
    - name: restart nginx
      service: name=nginx state=restarted
